# diagnostic_msgs/msg/DiagnosticArray (ROS 2 jazzy), generated by asterism_msggen.rb from
# DiagnosticArray.msg of the package diagnostic_msgs.
# License: Apache License 2.0, as the definition (package.xml of diagnostic_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("diagnostic_msgs/msg/DiagnosticStatus")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::DiagnosticMsgs
end

class ::Asterism::ROS::DiagnosticMsgs::DiagnosticArray < ::Asterism::ROS::Message
  ROS_NAME = "diagnostic_msgs/msg/DiagnosticArray"
  TYPE_NAME = "diagnostic_msgs::msg::dds_::DiagnosticArray_"
  TYPE_HASH = "RIHS01_5a8a36efb05fb25070fa0fb3810290c0e6cd4862b54a8fb975a1ee8dc55a333e"
  FIELDS = [:header, :status]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["status", "diagnostic_msgs/msg/DiagnosticStatus", "sequence", "diagnostic_msgs/msg/DiagnosticStatus", nil, nil]
  ]

  attr_accessor :header, :status

  def initialize(header: nil, status: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @status = status.nil? ? [] : status.map { |e| ::Asterism::ROS::DiagnosticMsgs::DiagnosticStatus.from(e) }
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.structs(::Asterism::ROS::DiagnosticMsgs::DiagnosticStatus, m.status, nil, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.status = r.structs(::Asterism::ROS::DiagnosticMsgs::DiagnosticStatus, nil)
    m
  end
end
