# diagnostic_msgs/msg/DiagnosticStatus (ROS 2 jazzy), generated by asterism_msggen.rb from
# DiagnosticStatus.msg of the package diagnostic_msgs.
# License: Apache License 2.0, as the definition (package.xml of diagnostic_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("diagnostic_msgs/msg/KeyValue")

module ::Asterism::ROS::DiagnosticMsgs
end

class ::Asterism::ROS::DiagnosticMsgs::DiagnosticStatus < ::Asterism::ROS::Message
  ROS_NAME = "diagnostic_msgs/msg/DiagnosticStatus"
  TYPE_NAME = "diagnostic_msgs::msg::dds_::DiagnosticStatus_"
  TYPE_HASH = "RIHS01_b0e3e692ea2d54a8af2f4ef1930e81556a2db55216b771f8a7d2724ed47bf0e4"
  FIELDS = [:level, :name, :message, :hardware_id, :values]
  FIELD_TYPES = [
    ["level", "byte", "scalar", nil, nil, nil],
    ["name", "string", "scalar", nil, nil, nil],
    ["message", "string", "scalar", nil, nil, nil],
    ["hardware_id", "string", "scalar", nil, nil, nil],
    ["values", "diagnostic_msgs/msg/KeyValue", "sequence", "diagnostic_msgs/msg/KeyValue", nil, nil]
  ]
  OK = 0
  WARN = 1
  ERROR = 2
  STALE = 3

  attr_accessor :level, :name, :message, :hardware_id, :values

  def initialize(level: nil, name: nil, message: nil, hardware_id: nil, values: nil)
    @level = level.nil? ? 0 : level
    @name = name.nil? ? "" : name
    @message = message.nil? ? "" : message
    @hardware_id = hardware_id.nil? ? "" : hardware_id
    @values = values.nil? ? [] : values.map { |e| ::Asterism::ROS::DiagnosticMsgs::KeyValue.from(e) }
  end

  def self.write(w, m)
    w.uint8(m.level)
    w.string(m.name)
    w.string(m.message)
    w.string(m.hardware_id)
    w.structs(::Asterism::ROS::DiagnosticMsgs::KeyValue, m.values, nil, nil)
  end

  def self.read(r)
    m = new
    m.level = r.uint8
    m.name = r.string
    m.message = r.string
    m.hardware_id = r.string
    m.values = r.structs(::Asterism::ROS::DiagnosticMsgs::KeyValue, nil)
    m
  end
end
