# diagnostic_msgs/msg/KeyValue (ROS 2 jazzy), generated by asterism_msggen.rb from
# KeyValue.msg of the package diagnostic_msgs.
# License: Apache License 2.0, as the definition (package.xml of diagnostic_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::DiagnosticMsgs
end

class ::Asterism::ROS::DiagnosticMsgs::KeyValue < ::Asterism::ROS::Message
  ROS_NAME = "diagnostic_msgs/msg/KeyValue"
  TYPE_NAME = "diagnostic_msgs::msg::dds_::KeyValue_"
  TYPE_HASH = "RIHS01_d68081eaa540288c5440753baecef0c4e16e81a5f78ad68902ded5100413bb42"
  FIELDS = [:key, :value]
  FIELD_TYPES = [
    ["key", "string", "scalar", nil, nil, nil],
    ["value", "string", "scalar", nil, nil, nil]
  ]

  attr_accessor :key, :value

  def initialize(key: nil, value: nil)
    @key = key.nil? ? "" : key
    @value = value.nil? ? "" : value
  end

  def self.write(w, m)
    w.string(m.key)
    w.string(m.value)
  end

  def self.read(r)
    m = new
    m.key = r.string
    m.value = r.string
    m
  end
end
