# std_msgs/msg/Bool (ROS 2 jazzy), generated by asterism_msggen.rb from
# Bool.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Bool < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Bool"
  TYPE_NAME = "std_msgs::msg::dds_::Bool_"
  TYPE_HASH = "RIHS01_feb91e995ff9ebd09c0cb3d2aed18b11077585839fb5db80193b62d74528f6c9"
  FIELDS = [:data]
  FIELD_TYPES = [
    ["data", "bool", "scalar", nil, nil, nil]
  ]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? false : data
  end

  def self.write(w, m)
    w.bool(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.bool
    m
  end
end
