# std_msgs/msg/Byte (ROS 2 jazzy), generated by asterism_msggen.rb from
# Byte.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Byte < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Byte"
  TYPE_NAME = "std_msgs::msg::dds_::Byte_"
  TYPE_HASH = "RIHS01_41e1a3345f73fe93ede006da826a6ee274af23dd4653976ff249b0f44e3e798f"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.uint8(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.uint8
    m
  end
end
