# std_msgs/msg/Char (ROS 2 jazzy), generated by asterism_msggen.rb from
# Char.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Char < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Char"
  TYPE_NAME = "std_msgs::msg::dds_::Char_"
  TYPE_HASH = "RIHS01_3ad2d04dd29ba19d04b16659afa3ccaedd691914b02a64e82e252f2fa6a586a9"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.uint8(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.uint8
    m
  end
end
