# std_msgs/msg/ColorRGBA (ROS 2 jazzy), generated by asterism_msggen.rb from
# ColorRGBA.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::ColorRGBA < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/ColorRGBA"
  TYPE_NAME = "std_msgs::msg::dds_::ColorRGBA_"
  TYPE_HASH = "RIHS01_77a7a5b9ae477306097665106e0413ba74440245b1f3d0c6d6405fe5c7813fe8"
  FIELDS = [:r, :g, :b, :a]

  attr_accessor :r, :g, :b, :a

  def initialize(r: nil, g: nil, b: nil, a: nil)
    @r = r.nil? ? 0.0 : r
    @g = g.nil? ? 0.0 : g
    @b = b.nil? ? 0.0 : b
    @a = a.nil? ? 0.0 : a
  end

  def self.write(w, m)
    w.float32(m.r)
    w.float32(m.g)
    w.float32(m.b)
    w.float32(m.a)
  end

  def self.read(r)
    m = new
    m.r = r.float32
    m.g = r.float32
    m.b = r.float32
    m.a = r.float32
    m
  end
end
