# std_msgs/msg/Empty (ROS 2 jazzy), generated by asterism_msggen.rb from
# Empty.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Empty < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Empty"
  TYPE_NAME = "std_msgs::msg::dds_::Empty_"
  TYPE_HASH = "RIHS01_20b625256f32d5dbc0d04fee44f43c41e51c70d3502f84b4a08e7a9c26a96312"
  FIELDS = []

  def initialize
  end

  def self.write(w, m)
    w.uint8(0)
  end

  def self.read(r)
    r.uint8
    new
  end
end
