# std_msgs/msg/Float64 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Float64.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Float64 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Float64"
  TYPE_NAME = "std_msgs::msg::dds_::Float64_"
  TYPE_HASH = "RIHS01_705ba9c3d1a09df43737eb67095534de36fd426c0587779bda2bc51fe790182a"
  FIELDS = [:data]
  FIELD_TYPES = [
    ["data", "float64", "scalar", nil, nil, nil]
  ]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0.0 : data
  end

  def self.write(w, m)
    w.float64(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.float64
    m
  end
end
