# std_msgs/msg/Float32 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Float32.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Float32 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Float32"
  TYPE_NAME = "std_msgs::msg::dds_::Float32_"
  TYPE_HASH = "RIHS01_7170d3d8f841f7be3172ce5f4f59f3a4d7f63b0447e8b33327601ad64d83d6e2"
  FIELDS = [:data]
  FIELD_TYPES = [
    ["data", "float32", "scalar", nil, nil, nil]
  ]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0.0 : data
  end

  def self.write(w, m)
    w.float32(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.float32
    m
  end
end
