# std_msgs/msg/Header (ROS 2 jazzy), generated by asterism_msggen.rb from
# Header.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("builtin_interfaces/msg/Time")

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Header < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Header"
  TYPE_NAME = "std_msgs::msg::dds_::Header_"
  TYPE_HASH = "RIHS01_f49fb3ae2cf070f793645ff749683ac6b06203e41c891e17701b1cb597ce6a01"
  FIELDS = [:stamp, :frame_id]
  FIELD_TYPES = [
    ["stamp", "builtin_interfaces/msg/Time", "scalar", "builtin_interfaces/msg/Time", nil, nil],
    ["frame_id", "string", "scalar", nil, nil, nil]
  ]

  attr_accessor :stamp, :frame_id

  def initialize(stamp: nil, frame_id: nil)
    @stamp = ::Asterism::ROS::BuiltinInterfaces::Time.from(stamp)
    @frame_id = frame_id.nil? ? "" : frame_id
  end

  def self.write(w, m)
    ::Asterism::ROS::BuiltinInterfaces::Time.write(w, ::Asterism::ROS::BuiltinInterfaces::Time.from(m.stamp))
    w.string(m.frame_id)
  end

  def self.read(r)
    m = new
    m.stamp = ::Asterism::ROS::BuiltinInterfaces::Time.read(r)
    m.frame_id = r.string
    m
  end
end
