# std_msgs/msg/Int16 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Int16.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Int16 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Int16"
  TYPE_NAME = "std_msgs::msg::dds_::Int16_"
  TYPE_HASH = "RIHS01_1dcc3464e47c288a55f943a389d337cdb06804de3f5cd7a266b0de718eee17e5"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.int16(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.int16
    m
  end
end
