# std_msgs/msg/Int32 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Int32.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Int32 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Int32"
  TYPE_NAME = "std_msgs::msg::dds_::Int32_"
  TYPE_HASH = "RIHS01_b6578ded3c58c626cfe8d1a6fb6e04f706f97e9f03d2727c9ff4e74b1cef0deb"
  FIELDS = [:data]
  FIELD_TYPES = [
    ["data", "int32", "scalar", nil, nil, nil]
  ]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.int32(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.int32
    m
  end
end
