# std_msgs/msg/Int64 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Int64.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Int64 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Int64"
  TYPE_NAME = "std_msgs::msg::dds_::Int64_"
  TYPE_HASH = "RIHS01_8cd1048c2f186b6bd9a92472dc1ce51723c0833a221e2b7aecfff111774f4b49"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.int64(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.int64
    m
  end
end
