# std_msgs/msg/Int8MultiArray (ROS 2 jazzy), generated by asterism_msggen.rb from
# Int8MultiArray.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/MultiArrayLayout")

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Int8MultiArray < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Int8MultiArray"
  TYPE_NAME = "std_msgs::msg::dds_::Int8MultiArray_"
  TYPE_HASH = "RIHS01_f21998d4b492abd63330765d75d5831238d400740386f651f13a872a4d2188db"
  FIELDS = [:layout, :data]
  FIELD_TYPES = [
    ["layout", "std_msgs/msg/MultiArrayLayout", "scalar", "std_msgs/msg/MultiArrayLayout", nil, nil],
    ["data", "int8", "sequence", nil, nil, nil]
  ]

  attr_accessor :layout, :data

  def initialize(layout: nil, data: nil)
    @layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(layout)
    @data = data.nil? ? [] : data
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::MultiArrayLayout.write(w, ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(m.layout))
    w.array(:int8, m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.read(r)
    m.data = r.array(:int8, nil)
    m
  end
end
