# std_msgs/msg/Int8 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Int8.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::Int8 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/Int8"
  TYPE_NAME = "std_msgs::msg::dds_::Int8_"
  TYPE_HASH = "RIHS01_26525065a403d972cb672f0777e333f0c799ad444ae5fcd79e43d1e73bd0f440"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.int8(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.int8
    m
  end
end
