# std_msgs/msg/MultiArrayDimension (ROS 2 jazzy), generated by asterism_msggen.rb from
# MultiArrayDimension.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::MultiArrayDimension < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/MultiArrayDimension"
  TYPE_NAME = "std_msgs::msg::dds_::MultiArrayDimension_"
  TYPE_HASH = "RIHS01_5e773a60a4c7fc8a54985f307c7837aa2994252a126c301957a24e31282c9cbe"
  FIELDS = [:label, :size, :stride]
  FIELD_TYPES = [
    ["label", "string", "scalar", nil, nil, nil],
    ["size", "uint32", "scalar", nil, nil, nil],
    ["stride", "uint32", "scalar", nil, nil, nil]
  ]

  attr_accessor :label, :size, :stride

  def initialize(label: nil, size: nil, stride: nil)
    @label = label.nil? ? "" : label
    @size = size.nil? ? 0 : size
    @stride = stride.nil? ? 0 : stride
  end

  def self.write(w, m)
    w.string(m.label)
    w.uint32(m.size)
    w.uint32(m.stride)
  end

  def self.read(r)
    m = new
    m.label = r.string
    m.size = r.uint32
    m.stride = r.uint32
    m
  end
end
