# std_msgs/msg/MultiArrayLayout (ROS 2 jazzy), generated by asterism_msggen.rb from
# MultiArrayLayout.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/MultiArrayDimension")

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::MultiArrayLayout < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/MultiArrayLayout"
  TYPE_NAME = "std_msgs::msg::dds_::MultiArrayLayout_"
  TYPE_HASH = "RIHS01_4c66e6f78e740ac103a94cf63259f968e48c617e7699e829b63c21a5cb50dac6"
  FIELDS = [:dim, :data_offset]

  attr_accessor :dim, :data_offset

  def initialize(dim: nil, data_offset: nil)
    @dim = dim.nil? ? [] : dim.map { |e| ::Asterism::ROS::StdMsgs::MultiArrayDimension.from(e) }
    @data_offset = data_offset.nil? ? 0 : data_offset
  end

  def self.write(w, m)
    w.structs(::Asterism::ROS::StdMsgs::MultiArrayDimension, m.dim, nil, nil)
    w.uint32(m.data_offset)
  end

  def self.read(r)
    m = new
    m.dim = r.structs(::Asterism::ROS::StdMsgs::MultiArrayDimension, nil)
    m.data_offset = r.uint32
    m
  end
end
