# std_msgs/msg/String (ROS 2 jazzy), generated by asterism_msggen.rb from
# String.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::String < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/String"
  TYPE_NAME = "std_msgs::msg::dds_::String_"
  TYPE_HASH = "RIHS01_df668c740482bbd48fb39d76a70dfd4bd59db1288021743503259e948f6b1a18"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? "" : data
  end

  def self.write(w, m)
    w.string(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.string
    m
  end
end
