# std_msgs/msg/UInt64 (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt64.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt64 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt64"
  TYPE_NAME = "std_msgs::msg::dds_::UInt64_"
  TYPE_HASH = "RIHS01_fbdc52018fc13755dce18024d1a671c856aa8b4aaf63adfb095b608f98e8c943"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.uint64(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.uint64
    m
  end
end
