# std_msgs/msg/UInt64MultiArray (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt64MultiArray.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/MultiArrayLayout")

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt64MultiArray < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt64MultiArray"
  TYPE_NAME = "std_msgs::msg::dds_::UInt64MultiArray_"
  TYPE_HASH = "RIHS01_fc1c685c2f76bdc6983da025cb25d2db5fb5157b059e300f6d957d86f981b366"
  FIELDS = [:layout, :data]

  attr_accessor :layout, :data

  def initialize(layout: nil, data: nil)
    @layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(layout)
    @data = data.nil? ? [] : data
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::MultiArrayLayout.write(w, ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(m.layout))
    w.array(:uint64, m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.read(r)
    m.data = r.array(:uint64, nil)
    m
  end
end
