# std_msgs/msg/UInt8 (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt8.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt8 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt8"
  TYPE_NAME = "std_msgs::msg::dds_::UInt8_"
  TYPE_HASH = "RIHS01_6138bd83d8c3569cb80a667db03cfc1629f529fee79d944c39c34e352e72f010"
  FIELDS = [:data]
  FIELD_TYPES = [
    ["data", "uint8", "scalar", nil, nil, nil]
  ]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.uint8(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.uint8
    m
  end
end
