# std_msgs/msg/UInt8MultiArray (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt8MultiArray.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/MultiArrayLayout")

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt8MultiArray < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt8MultiArray"
  TYPE_NAME = "std_msgs::msg::dds_::UInt8MultiArray_"
  TYPE_HASH = "RIHS01_5687e861b8d307a5e48b7515467ae7a5fc2daf805bd0ce6d8e9e604bade9f385"
  FIELDS = [:layout, :data]
  FIELD_TYPES = [
    ["layout", "std_msgs/msg/MultiArrayLayout", "scalar", "std_msgs/msg/MultiArrayLayout", nil, nil],
    ["data", "uint8", "sequence", nil, nil, nil]
  ]

  attr_accessor :layout, :data

  def initialize(layout: nil, data: nil)
    @layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(layout)
    @data = data.nil? ? "" : data
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::MultiArrayLayout.write(w, ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(m.layout))
    w.bytes(m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.read(r)
    m.data = r.bytes(nil)
    m
  end
end
