# std_msgs/msg/UInt32 (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt32.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt32 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt32"
  TYPE_NAME = "std_msgs::msg::dds_::UInt32_"
  TYPE_HASH = "RIHS01_a5c874829b752bc5fa190024b0ad76f578cc278271e855c7d02a818b3516fb4a"
  FIELDS = [:data]
  FIELD_TYPES = [
    ["data", "uint32", "scalar", nil, nil, nil]
  ]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.uint32(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.uint32
    m
  end
end
