# std_msgs/msg/UInt32MultiArray (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt32MultiArray.msg of the package std_msgs.
# License: Apache License 2.0, as the definition (package.xml of std_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/MultiArrayLayout")

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt32MultiArray < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt32MultiArray"
  TYPE_NAME = "std_msgs::msg::dds_::UInt32MultiArray_"
  TYPE_HASH = "RIHS01_6c2577c7ad3cbdcc2164a41c12f1d5ad314ea320f3fb1ee47e78019fe16bb5b0"
  FIELDS = [:layout, :data]
  FIELD_TYPES = [
    ["layout", "std_msgs/msg/MultiArrayLayout", "scalar", "std_msgs/msg/MultiArrayLayout", nil, nil],
    ["data", "uint32", "sequence", nil, nil, nil]
  ]

  attr_accessor :layout, :data

  def initialize(layout: nil, data: nil)
    @layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(layout)
    @data = data.nil? ? [] : data
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::MultiArrayLayout.write(w, ::Asterism::ROS::StdMsgs::MultiArrayLayout.from(m.layout))
    w.array(:uint32, m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.layout = ::Asterism::ROS::StdMsgs::MultiArrayLayout.read(r)
    m.data = r.array(:uint32, nil)
    m
  end
end
