# geometry_msgs/msg/Accel (ROS 2 jazzy), generated by asterism_msggen.rb from
# Accel.msg. Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Vector3")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Accel < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Accel"
  TYPE_NAME = "geometry_msgs::msg::dds_::Accel_"
  TYPE_HASH = "RIHS01_dc448243ded9b1fcbcca24aba0c22f013dae06c354ba2d849571c0a2a3f57ca0"
  FIELDS = [:linear, :angular]

  attr_accessor :linear, :angular

  def initialize(linear: nil, angular: nil)
    @linear = ::Asterism::ROS::GeometryMsgs::Vector3.from(linear)
    @angular = ::Asterism::ROS::GeometryMsgs::Vector3.from(angular)
  end

  def self.write(w, m)
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.linear))
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.angular))
  end

  def self.read(r)
    m = new
    m.linear = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m.angular = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m
  end
end
