# geometry_msgs/msg/Point (ROS 2 jazzy), generated by asterism_msggen.rb from
# Point.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Point < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Point"
  TYPE_NAME = "geometry_msgs::msg::dds_::Point_"
  TYPE_HASH = "RIHS01_6963084842a9b04494d6b2941d11444708d892da2f4b09843b9c43f42a7f6881"
  FIELDS = [:x, :y, :z]

  attr_accessor :x, :y, :z

  def initialize(x: nil, y: nil, z: nil)
    @x = x.nil? ? 0.0 : x
    @y = y.nil? ? 0.0 : y
    @z = z.nil? ? 0.0 : z
  end

  def self.write(w, m)
    w.float64(m.x)
    w.float64(m.y)
    w.float64(m.z)
  end

  def self.read(r)
    m = new
    m.x = r.float64
    m.y = r.float64
    m.z = r.float64
    m
  end
end
