# geometry_msgs/msg/PoseWithCovariance (ROS 2 jazzy), generated by asterism_msggen.rb from
# PoseWithCovariance.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Pose")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::PoseWithCovariance < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/PoseWithCovariance"
  TYPE_NAME = "geometry_msgs::msg::dds_::PoseWithCovariance_"
  TYPE_HASH = "RIHS01_9a7c0fd234b7f45c6098745ecccd773ca1085670e64107135397aee31c02e1bb"
  FIELDS = [:pose, :covariance]
  FIELD_TYPES = [
    ["pose", "geometry_msgs/msg/Pose", "scalar", "geometry_msgs/msg/Pose", nil, nil],
    ["covariance", "float64", "array", nil, 36, nil]
  ]

  attr_accessor :pose, :covariance

  def initialize(pose: nil, covariance: nil)
    @pose = ::Asterism::ROS::GeometryMsgs::Pose.from(pose)
    @covariance = covariance.nil? ? ::Array.new(36, 0.0) : covariance
  end

  def self.write(w, m)
    ::Asterism::ROS::GeometryMsgs::Pose.write(w, ::Asterism::ROS::GeometryMsgs::Pose.from(m.pose))
    w.array(:float64, m.covariance, 36, nil)
  end

  def self.read(r)
    m = new
    m.pose = ::Asterism::ROS::GeometryMsgs::Pose.read(r)
    m.covariance = r.array(:float64, 36)
    m
  end
end
