# geometry_msgs/msg/Pose2D (ROS 2 jazzy), generated by asterism_msggen.rb from
# Pose2D.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Pose2D < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Pose2D"
  TYPE_NAME = "geometry_msgs::msg::dds_::Pose2D_"
  TYPE_HASH = "RIHS01_d68efa5b46e70f7b16ca23085474fdac5a44b638783ec42f661da64da4724ccc"
  FIELDS = [:x, :y, :theta]

  attr_accessor :x, :y, :theta

  def initialize(x: nil, y: nil, theta: nil)
    @x = x.nil? ? 0.0 : x
    @y = y.nil? ? 0.0 : y
    @theta = theta.nil? ? 0.0 : theta
  end

  def self.write(w, m)
    w.float64(m.x)
    w.float64(m.y)
    w.float64(m.theta)
  end

  def self.read(r)
    m = new
    m.x = r.float64
    m.y = r.float64
    m.theta = r.float64
    m
  end
end
