# geometry_msgs/msg/PoseStamped (ROS 2 jazzy), generated by asterism_msggen.rb from
# PoseStamped.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Pose")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::PoseStamped < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/PoseStamped"
  TYPE_NAME = "geometry_msgs::msg::dds_::PoseStamped_"
  TYPE_HASH = "RIHS01_10f3786d7d40fd2b54367835614bff85d4ad3b5dab62bf8bca0cc232d73b4cd8"
  FIELDS = [:header, :pose]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["pose", "geometry_msgs/msg/Pose", "scalar", "geometry_msgs/msg/Pose", nil, nil]
  ]

  attr_accessor :header, :pose

  def initialize(header: nil, pose: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @pose = ::Asterism::ROS::GeometryMsgs::Pose.from(pose)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::GeometryMsgs::Pose.write(w, ::Asterism::ROS::GeometryMsgs::Pose.from(m.pose))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.pose = ::Asterism::ROS::GeometryMsgs::Pose.read(r)
    m
  end
end
