# geometry_msgs/msg/Quaternion (ROS 2 jazzy), generated by asterism_msggen.rb from
# Quaternion.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Quaternion < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Quaternion"
  TYPE_NAME = "geometry_msgs::msg::dds_::Quaternion_"
  TYPE_HASH = "RIHS01_8a765f66778c8ff7c8ab94afcc590a2ed5325a1d9a076ffff38fbce36f458684"
  FIELDS = [:x, :y, :z, :w]

  attr_accessor :x, :y, :z, :w

  def initialize(x: nil, y: nil, z: nil, w: nil)
    @x = x.nil? ? 0.0 : x
    @y = y.nil? ? 0.0 : y
    @z = z.nil? ? 0.0 : z
    @w = w.nil? ? 1.0 : w
  end

  def self.write(w, m)
    w.float64(m.x)
    w.float64(m.y)
    w.float64(m.z)
    w.float64(m.w)
  end

  def self.read(r)
    m = new
    m.x = r.float64
    m.y = r.float64
    m.z = r.float64
    m.w = r.float64
    m
  end
end
