# geometry_msgs/msg/TransformStamped (ROS 2 jazzy), generated by asterism_msggen.rb from
# TransformStamped.msg. Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Transform")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::TransformStamped < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/TransformStamped"
  TYPE_NAME = "geometry_msgs::msg::dds_::TransformStamped_"
  TYPE_HASH = "RIHS01_0a241f87d04668d94099cbb5ba11691d5ad32c2f29682e4eb5653424bd275206"
  FIELDS = [:header, :child_frame_id, :transform]

  attr_accessor :header, :child_frame_id, :transform

  def initialize(header: nil, child_frame_id: nil, transform: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @child_frame_id = child_frame_id.nil? ? "" : child_frame_id
    @transform = ::Asterism::ROS::GeometryMsgs::Transform.from(transform)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.string(m.child_frame_id)
    ::Asterism::ROS::GeometryMsgs::Transform.write(w, ::Asterism::ROS::GeometryMsgs::Transform.from(m.transform))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.child_frame_id = r.string
    m.transform = ::Asterism::ROS::GeometryMsgs::Transform.read(r)
    m
  end
end
