# geometry_msgs/msg/Twist (ROS 2 jazzy), generated by asterism_msggen.rb from
# Twist.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Vector3")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Twist < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Twist"
  TYPE_NAME = "geometry_msgs::msg::dds_::Twist_"
  TYPE_HASH = "RIHS01_9c45bf16fe0983d80e3cfe750d6835843d265a9a6c46bd2e609fcddde6fb8d2a"
  FIELDS = [:linear, :angular]
  FIELD_TYPES = [
    ["linear", "geometry_msgs/msg/Vector3", "scalar", "geometry_msgs/msg/Vector3", nil, nil],
    ["angular", "geometry_msgs/msg/Vector3", "scalar", "geometry_msgs/msg/Vector3", nil, nil]
  ]

  attr_accessor :linear, :angular

  def initialize(linear: nil, angular: nil)
    @linear = ::Asterism::ROS::GeometryMsgs::Vector3.from(linear)
    @angular = ::Asterism::ROS::GeometryMsgs::Vector3.from(angular)
  end

  def self.write(w, m)
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.linear))
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.angular))
  end

  def self.read(r)
    m = new
    m.linear = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m.angular = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m
  end
end
