# geometry_msgs/msg/TwistStamped (ROS 2 jazzy), generated by asterism_msggen.rb from
# TwistStamped.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Twist")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::TwistStamped < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/TwistStamped"
  TYPE_NAME = "geometry_msgs::msg::dds_::TwistStamped_"
  TYPE_HASH = "RIHS01_5f0fcd4f81d5d06ad9b4c4c63e3ea51b82d6ae4d0558f1d475229b1121db6f64"
  FIELDS = [:header, :twist]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["twist", "geometry_msgs/msg/Twist", "scalar", "geometry_msgs/msg/Twist", nil, nil]
  ]

  attr_accessor :header, :twist

  def initialize(header: nil, twist: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @twist = ::Asterism::ROS::GeometryMsgs::Twist.from(twist)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::GeometryMsgs::Twist.write(w, ::Asterism::ROS::GeometryMsgs::Twist.from(m.twist))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.twist = ::Asterism::ROS::GeometryMsgs::Twist.read(r)
    m
  end
end
