# geometry_msgs/msg/TwistWithCovariance (ROS 2 jazzy), generated by asterism_msggen.rb from
# TwistWithCovariance.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Twist")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::TwistWithCovariance < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/TwistWithCovariance"
  TYPE_NAME = "geometry_msgs::msg::dds_::TwistWithCovariance_"
  TYPE_HASH = "RIHS01_49f574f033f095d8b6cd1beaca5ca7925e296e84af1716d16c89d38b059c8c18"
  FIELDS = [:twist, :covariance]
  FIELD_TYPES = [
    ["twist", "geometry_msgs/msg/Twist", "scalar", "geometry_msgs/msg/Twist", nil, nil],
    ["covariance", "float64", "array", nil, 36, nil]
  ]

  attr_accessor :twist, :covariance

  def initialize(twist: nil, covariance: nil)
    @twist = ::Asterism::ROS::GeometryMsgs::Twist.from(twist)
    @covariance = covariance.nil? ? ::Array.new(36, 0.0) : covariance
  end

  def self.write(w, m)
    ::Asterism::ROS::GeometryMsgs::Twist.write(w, ::Asterism::ROS::GeometryMsgs::Twist.from(m.twist))
    w.array(:float64, m.covariance, 36, nil)
  end

  def self.read(r)
    m = new
    m.twist = ::Asterism::ROS::GeometryMsgs::Twist.read(r)
    m.covariance = r.array(:float64, 36)
    m
  end
end
