# geometry_msgs/msg/Vector3Stamped (ROS 2 jazzy), generated by asterism_msggen.rb from
# Vector3Stamped.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Vector3")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Vector3Stamped < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Vector3Stamped"
  TYPE_NAME = "geometry_msgs::msg::dds_::Vector3Stamped_"
  TYPE_HASH = "RIHS01_d4829622288cbb443886e7ea94ea5671a3b1be6bab4ad04224432a65f7d7887a"
  FIELDS = [:header, :vector]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["vector", "geometry_msgs/msg/Vector3", "scalar", "geometry_msgs/msg/Vector3", nil, nil]
  ]

  attr_accessor :header, :vector

  def initialize(header: nil, vector: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @vector = ::Asterism::ROS::GeometryMsgs::Vector3.from(vector)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.vector))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.vector = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m
  end
end
