# geometry_msgs/msg/Wrench (ROS 2 jazzy), generated by asterism_msggen.rb from
# Wrench.msg of the package geometry_msgs.
# License: Apache License 2.0, as the definition (package.xml of geometry_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Vector3")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Wrench < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Wrench"
  TYPE_NAME = "geometry_msgs::msg::dds_::Wrench_"
  TYPE_HASH = "RIHS01_018e8519d57c16adbe97c9fe1460ef21fec7e31bc541de3d653a35895677ce52"
  FIELDS = [:force, :torque]

  attr_accessor :force, :torque

  def initialize(force: nil, torque: nil)
    @force = ::Asterism::ROS::GeometryMsgs::Vector3.from(force)
    @torque = ::Asterism::ROS::GeometryMsgs::Vector3.from(torque)
  end

  def self.write(w, m)
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.force))
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.torque))
  end

  def self.read(r)
    m = new
    m.force = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m.torque = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m
  end
end
