# visualization_msgs/msg/Marker (ROS 2 jazzy), generated by asterism_msggen.rb from
# Marker.msg of the package visualization_msgs.
# License: Apache License 2.0, as the definition (package.xml of visualization_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("builtin_interfaces/msg/Duration")
::Asterism::ROS.require_type("geometry_msgs/msg/Point")
::Asterism::ROS.require_type("geometry_msgs/msg/Pose")
::Asterism::ROS.require_type("geometry_msgs/msg/Vector3")
::Asterism::ROS.require_type("sensor_msgs/msg/CompressedImage")
::Asterism::ROS.require_type("std_msgs/msg/ColorRGBA")
::Asterism::ROS.require_type("std_msgs/msg/Header")
::Asterism::ROS.require_type("visualization_msgs/msg/MeshFile")
::Asterism::ROS.require_type("visualization_msgs/msg/UVCoordinate")

module ::Asterism::ROS::VisualizationMsgs
end

class ::Asterism::ROS::VisualizationMsgs::Marker < ::Asterism::ROS::Message
  ROS_NAME = "visualization_msgs/msg/Marker"
  TYPE_NAME = "visualization_msgs::msg::dds_::Marker_"
  TYPE_HASH = "RIHS01_45b13ccf791f225962bf74e746f9644518855d783a6f42ba0cc14fde2b4f3ce0"
  FIELDS = [:header, :ns, :id, :type, :action, :pose, :scale, :color, :lifetime, :frame_locked, :points, :colors, :texture_resource, :texture, :uv_coordinates, :text, :mesh_resource, :mesh_file, :mesh_use_embedded_materials]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["ns", "string", "scalar", nil, nil, nil],
    ["id", "int32", "scalar", nil, nil, nil],
    ["type", "int32", "scalar", nil, nil, nil],
    ["action", "int32", "scalar", nil, nil, nil],
    ["pose", "geometry_msgs/msg/Pose", "scalar", "geometry_msgs/msg/Pose", nil, nil],
    ["scale", "geometry_msgs/msg/Vector3", "scalar", "geometry_msgs/msg/Vector3", nil, nil],
    ["color", "std_msgs/msg/ColorRGBA", "scalar", "std_msgs/msg/ColorRGBA", nil, nil],
    ["lifetime", "builtin_interfaces/msg/Duration", "scalar", "builtin_interfaces/msg/Duration", nil, nil],
    ["frame_locked", "bool", "scalar", nil, nil, nil],
    ["points", "geometry_msgs/msg/Point", "sequence", "geometry_msgs/msg/Point", nil, nil],
    ["colors", "std_msgs/msg/ColorRGBA", "sequence", "std_msgs/msg/ColorRGBA", nil, nil],
    ["texture_resource", "string", "scalar", nil, nil, nil],
    ["texture", "sensor_msgs/msg/CompressedImage", "scalar", "sensor_msgs/msg/CompressedImage", nil, nil],
    ["uv_coordinates", "visualization_msgs/msg/UVCoordinate", "sequence", "visualization_msgs/msg/UVCoordinate", nil, nil],
    ["text", "string", "scalar", nil, nil, nil],
    ["mesh_resource", "string", "scalar", nil, nil, nil],
    ["mesh_file", "visualization_msgs/msg/MeshFile", "scalar", "visualization_msgs/msg/MeshFile", nil, nil],
    ["mesh_use_embedded_materials", "bool", "scalar", nil, nil, nil]
  ]
  ARROW = 0
  CUBE = 1
  SPHERE = 2
  CYLINDER = 3
  LINE_STRIP = 4
  LINE_LIST = 5
  CUBE_LIST = 6
  SPHERE_LIST = 7
  POINTS = 8
  TEXT_VIEW_FACING = 9
  MESH_RESOURCE = 10
  TRIANGLE_LIST = 11
  ARROW_STRIP = 12
  ADD = 0
  MODIFY = 0
  DELETE = 2
  DELETEALL = 3

  attr_accessor :header, :ns, :id, :type, :action, :pose, :scale, :color, :lifetime, :frame_locked, :points, :colors, :texture_resource, :texture, :uv_coordinates, :text, :mesh_resource, :mesh_file, :mesh_use_embedded_materials

  def initialize(header: nil, ns: nil, id: nil, type: nil, action: nil, pose: nil, scale: nil, color: nil, lifetime: nil, frame_locked: nil, points: nil, colors: nil, texture_resource: nil, texture: nil, uv_coordinates: nil, text: nil, mesh_resource: nil, mesh_file: nil, mesh_use_embedded_materials: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @ns = ns.nil? ? "" : ns
    @id = id.nil? ? 0 : id
    @type = type.nil? ? 0 : type
    @action = action.nil? ? 0 : action
    @pose = ::Asterism::ROS::GeometryMsgs::Pose.from(pose)
    @scale = ::Asterism::ROS::GeometryMsgs::Vector3.from(scale)
    @color = ::Asterism::ROS::StdMsgs::ColorRGBA.from(color)
    @lifetime = ::Asterism::ROS::BuiltinInterfaces::Duration.from(lifetime)
    @frame_locked = frame_locked.nil? ? false : frame_locked
    @points = points.nil? ? [] : points.map { |e| ::Asterism::ROS::GeometryMsgs::Point.from(e) }
    @colors = colors.nil? ? [] : colors.map { |e| ::Asterism::ROS::StdMsgs::ColorRGBA.from(e) }
    @texture_resource = texture_resource.nil? ? "" : texture_resource
    @texture = ::Asterism::ROS::SensorMsgs::CompressedImage.from(texture)
    @uv_coordinates = uv_coordinates.nil? ? [] : uv_coordinates.map { |e| ::Asterism::ROS::VisualizationMsgs::UVCoordinate.from(e) }
    @text = text.nil? ? "" : text
    @mesh_resource = mesh_resource.nil? ? "" : mesh_resource
    @mesh_file = ::Asterism::ROS::VisualizationMsgs::MeshFile.from(mesh_file)
    @mesh_use_embedded_materials = mesh_use_embedded_materials.nil? ? false : mesh_use_embedded_materials
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.string(m.ns)
    w.int32(m.id)
    w.int32(m.type)
    w.int32(m.action)
    ::Asterism::ROS::GeometryMsgs::Pose.write(w, ::Asterism::ROS::GeometryMsgs::Pose.from(m.pose))
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.scale))
    ::Asterism::ROS::StdMsgs::ColorRGBA.write(w, ::Asterism::ROS::StdMsgs::ColorRGBA.from(m.color))
    ::Asterism::ROS::BuiltinInterfaces::Duration.write(w, ::Asterism::ROS::BuiltinInterfaces::Duration.from(m.lifetime))
    w.bool(m.frame_locked)
    w.structs(::Asterism::ROS::GeometryMsgs::Point, m.points, nil, nil)
    w.structs(::Asterism::ROS::StdMsgs::ColorRGBA, m.colors, nil, nil)
    w.string(m.texture_resource)
    ::Asterism::ROS::SensorMsgs::CompressedImage.write(w, ::Asterism::ROS::SensorMsgs::CompressedImage.from(m.texture))
    w.structs(::Asterism::ROS::VisualizationMsgs::UVCoordinate, m.uv_coordinates, nil, nil)
    w.string(m.text)
    w.string(m.mesh_resource)
    ::Asterism::ROS::VisualizationMsgs::MeshFile.write(w, ::Asterism::ROS::VisualizationMsgs::MeshFile.from(m.mesh_file))
    w.bool(m.mesh_use_embedded_materials)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.ns = r.string
    m.id = r.int32
    m.type = r.int32
    m.action = r.int32
    m.pose = ::Asterism::ROS::GeometryMsgs::Pose.read(r)
    m.scale = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m.color = ::Asterism::ROS::StdMsgs::ColorRGBA.read(r)
    m.lifetime = ::Asterism::ROS::BuiltinInterfaces::Duration.read(r)
    m.frame_locked = r.bool
    m.points = r.structs(::Asterism::ROS::GeometryMsgs::Point, nil)
    m.colors = r.structs(::Asterism::ROS::StdMsgs::ColorRGBA, nil)
    m.texture_resource = r.string
    m.texture = ::Asterism::ROS::SensorMsgs::CompressedImage.read(r)
    m.uv_coordinates = r.structs(::Asterism::ROS::VisualizationMsgs::UVCoordinate, nil)
    m.text = r.string
    m.mesh_resource = r.string
    m.mesh_file = ::Asterism::ROS::VisualizationMsgs::MeshFile.read(r)
    m.mesh_use_embedded_materials = r.bool
    m
  end
end
