# visualization_msgs/msg/MarkerArray (ROS 2 jazzy), generated by asterism_msggen.rb from
# MarkerArray.msg of the package visualization_msgs.
# License: Apache License 2.0, as the definition (package.xml of visualization_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("visualization_msgs/msg/Marker")

module ::Asterism::ROS::VisualizationMsgs
end

class ::Asterism::ROS::VisualizationMsgs::MarkerArray < ::Asterism::ROS::Message
  ROS_NAME = "visualization_msgs/msg/MarkerArray"
  TYPE_NAME = "visualization_msgs::msg::dds_::MarkerArray_"
  TYPE_HASH = "RIHS01_86cb8800b6fb05b5eff1abd7a56f62a5641d3ae9a1c29e78e67e704f1d067dcf"
  FIELDS = [:markers]
  FIELD_TYPES = [
    ["markers", "visualization_msgs/msg/Marker", "sequence", "visualization_msgs/msg/Marker", nil, nil]
  ]

  attr_accessor :markers

  def initialize(markers: nil)
    @markers = markers.nil? ? [] : markers.map { |e| ::Asterism::ROS::VisualizationMsgs::Marker.from(e) }
  end

  def self.write(w, m)
    w.structs(::Asterism::ROS::VisualizationMsgs::Marker, m.markers, nil, nil)
  end

  def self.read(r)
    m = new
    m.markers = r.structs(::Asterism::ROS::VisualizationMsgs::Marker, nil)
    m
  end
end
