# visualization_msgs/msg/MeshFile (ROS 2 jazzy), generated by asterism_msggen.rb from
# MeshFile.msg of the package visualization_msgs.
# License: Apache License 2.0, as the definition (package.xml of visualization_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::VisualizationMsgs
end

class ::Asterism::ROS::VisualizationMsgs::MeshFile < ::Asterism::ROS::Message
  ROS_NAME = "visualization_msgs/msg/MeshFile"
  TYPE_NAME = "visualization_msgs::msg::dds_::MeshFile_"
  TYPE_HASH = "RIHS01_7710ece15a148fb7c9b546364cfb215bb06098087bd6394fe5b73a493508f8c4"
  FIELDS = [:filename, :data]
  FIELD_TYPES = [
    ["filename", "string", "scalar", nil, nil, nil],
    ["data", "uint8", "sequence", nil, nil, nil]
  ]

  attr_accessor :filename, :data

  def initialize(filename: nil, data: nil)
    @filename = filename.nil? ? "" : filename
    @data = data.nil? ? "" : data
  end

  def self.write(w, m)
    w.string(m.filename)
    w.bytes(m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.filename = r.string
    m.data = r.bytes(nil)
    m
  end
end
