# visualization_msgs/msg/UVCoordinate (ROS 2 jazzy), generated by asterism_msggen.rb from
# UVCoordinate.msg of the package visualization_msgs.
# License: Apache License 2.0, as the definition (package.xml of visualization_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::VisualizationMsgs
end

class ::Asterism::ROS::VisualizationMsgs::UVCoordinate < ::Asterism::ROS::Message
  ROS_NAME = "visualization_msgs/msg/UVCoordinate"
  TYPE_NAME = "visualization_msgs::msg::dds_::UVCoordinate_"
  TYPE_HASH = "RIHS01_f27f7ed21fe360c6066944f856b801a0c0d1e94e815b6886444b42d90b196a26"
  FIELDS = [:u, :v]
  FIELD_TYPES = [
    ["u", "float32", "scalar", nil, nil, nil],
    ["v", "float32", "scalar", nil, nil, nil]
  ]

  attr_accessor :u, :v

  def initialize(u: nil, v: nil)
    @u = u.nil? ? 0.0 : u
    @v = v.nil? ? 0.0 : v
  end

  def self.write(w, m)
    w.float32(m.u)
    w.float32(m.v)
  end

  def self.read(r)
    m = new
    m.u = r.float32
    m.v = r.float32
    m
  end
end
