# example_interfaces/srv/AddTwoInts (ROS 2 jazzy), generated by asterism_msggen.rb from
# AddTwoInts.srv of the package example_interfaces.
# License: Apache License 2.0, as the definition (package.xml of example_interfaces).
# Do not edit; regenerate instead.

module ::Asterism::ROS::ExampleInterfaces
end

# example_interfaces/srv/AddTwoInts: a service. Request and Response are its messages;
# TYPE_NAME and TYPE_HASH are the service's (what rmw_zenoh puts in keys).
module ::Asterism::ROS::ExampleInterfaces::AddTwoInts
  ROS_NAME = "example_interfaces/srv/AddTwoInts"
  TYPE_NAME = "example_interfaces::srv::dds_::AddTwoInts_"
  TYPE_HASH = "RIHS01_e118de6bf5eeb66a2491b5bda11202e7b68f198d6f67922cf30364858239c81a"
end

class ::Asterism::ROS::ExampleInterfaces::AddTwoInts::Request < ::Asterism::ROS::Message
  ROS_NAME = "example_interfaces/srv/AddTwoInts_Request"
  TYPE_NAME = "example_interfaces::srv::dds_::AddTwoInts_Request_"
  TYPE_HASH = "RIHS01_000c5fd92d6b2e1a05949348f584d6d652adea1e92d691792011ac2273508302"
  FIELDS = [:a, :b]

  attr_accessor :a, :b

  def initialize(a: nil, b: nil)
    @a = a.nil? ? 0 : a
    @b = b.nil? ? 0 : b
  end

  def self.write(w, m)
    w.int64(m.a)
    w.int64(m.b)
  end

  def self.read(r)
    m = new
    m.a = r.int64
    m.b = r.int64
    m
  end
end

class ::Asterism::ROS::ExampleInterfaces::AddTwoInts::Response < ::Asterism::ROS::Message
  ROS_NAME = "example_interfaces/srv/AddTwoInts_Response"
  TYPE_NAME = "example_interfaces::srv::dds_::AddTwoInts_Response_"
  TYPE_HASH = "RIHS01_de5c030d4af33cba2749310b249737b631594703f9300495f48bffb2b44dcc2f"
  FIELDS = [:sum]

  attr_accessor :sum

  def initialize(sum: nil)
    @sum = sum.nil? ? 0 : sum
  end

  def self.write(w, m)
    w.int64(m.sum)
  end

  def self.read(r)
    m = new
    m.sum = r.int64
    m
  end
end
