# builtin_interfaces/msg/Duration (ROS 2 jazzy), generated by asterism_msggen.rb from
# Duration.msg of the package builtin_interfaces.
# License: Apache License 2.0, as the definition (package.xml of builtin_interfaces).
# Do not edit; regenerate instead.

module ::Asterism::ROS::BuiltinInterfaces
end

class ::Asterism::ROS::BuiltinInterfaces::Duration < ::Asterism::ROS::Message
  ROS_NAME = "builtin_interfaces/msg/Duration"
  TYPE_NAME = "builtin_interfaces::msg::dds_::Duration_"
  TYPE_HASH = "RIHS01_e8d009f659816f758b75334ee1a9ca5b5c0b859843261f14c7f937349599d93b"
  FIELDS = [:sec, :nanosec]
  FIELD_TYPES = [
    ["sec", "int32", "scalar", nil, nil, nil],
    ["nanosec", "uint32", "scalar", nil, nil, nil]
  ]

  attr_accessor :sec, :nanosec

  def initialize(sec: nil, nanosec: nil)
    @sec = sec.nil? ? 0 : sec
    @nanosec = nanosec.nil? ? 0 : nanosec
  end

  def self.write(w, m)
    w.int32(m.sec)
    w.uint32(m.nanosec)
  end

  def self.read(r)
    m = new
    m.sec = r.int32
    m.nanosec = r.uint32
    m
  end
end
