# builtin_interfaces/msg/Time (ROS 2 jazzy), generated by asterism_msggen.rb from
# Time.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::BuiltinInterfaces
end

class ::Asterism::ROS::BuiltinInterfaces::Time < ::Asterism::ROS::Message
  ROS_NAME = "builtin_interfaces/msg/Time"
  TYPE_NAME = "builtin_interfaces::msg::dds_::Time_"
  TYPE_HASH = "RIHS01_b106235e25a4c5ed35098aa0a61a3ee9c9b18d197f398b0e4206cea9acf9c197"
  FIELDS = [:sec, :nanosec]

  attr_accessor :sec, :nanosec

  def initialize(sec: nil, nanosec: nil)
    @sec = sec.nil? ? 0 : sec
    @nanosec = nanosec.nil? ? 0 : nanosec
  end

  def self.write(w, m)
    w.int32(m.sec)
    w.uint32(m.nanosec)
  end

  def self.read(r)
    m = new
    m.sec = r.int32
    m.nanosec = r.uint32
    m
  end
end
