# geometry_msgs/msg/Point32 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Point32.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Point32 < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Point32"
  TYPE_NAME = "geometry_msgs::msg::dds_::Point32_"
  TYPE_HASH = "RIHS01_2fc4db7cae16a4582c79a56b66173a8d48d52c7dc520ddc55a0d4bcf2a4bfdbc"
  FIELDS = [:x, :y, :z]

  attr_accessor :x, :y, :z

  def initialize(x: nil, y: nil, z: nil)
    @x = x.nil? ? 0.0 : x
    @y = y.nil? ? 0.0 : y
    @z = z.nil? ? 0.0 : z
  end

  def self.write(w, m)
    w.float32(m.x)
    w.float32(m.y)
    w.float32(m.z)
  end

  def self.read(r)
    m = new
    m.x = r.float32
    m.y = r.float32
    m.z = r.float32
    m
  end
end
