# geometry_msgs/msg/QuaternionStamped (ROS 2 jazzy), generated by asterism_msggen.rb from
# QuaternionStamped.msg. Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Quaternion")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::QuaternionStamped < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/QuaternionStamped"
  TYPE_NAME = "geometry_msgs::msg::dds_::QuaternionStamped_"
  TYPE_HASH = "RIHS01_381add86c6c3160644d228ca342182c7fd6c7fab11c7a85ad817a9cc22dbac6e"
  FIELDS = [:header, :quaternion]

  attr_accessor :header, :quaternion

  def initialize(header: nil, quaternion: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @quaternion = ::Asterism::ROS::GeometryMsgs::Quaternion.from(quaternion)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::GeometryMsgs::Quaternion.write(w, ::Asterism::ROS::GeometryMsgs::Quaternion.from(m.quaternion))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.quaternion = ::Asterism::ROS::GeometryMsgs::Quaternion.read(r)
    m
  end
end
