# geometry_msgs/msg/Vector3 (ROS 2 jazzy), generated by asterism_msggen.rb from
# Vector3.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::Vector3 < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/Vector3"
  TYPE_NAME = "geometry_msgs::msg::dds_::Vector3_"
  TYPE_HASH = "RIHS01_cc12fe83e4c02719f1ce8070bfd14aecd40f75a96696a67a2a1f37f7dbb0765d"
  FIELDS = [:x, :y, :z]

  attr_accessor :x, :y, :z

  def initialize(x: nil, y: nil, z: nil)
    @x = x.nil? ? 0.0 : x
    @y = y.nil? ? 0.0 : y
    @z = z.nil? ? 0.0 : z
  end

  def self.write(w, m)
    w.float64(m.x)
    w.float64(m.y)
    w.float64(m.z)
  end

  def self.read(r)
    m = new
    m.x = r.float64
    m.y = r.float64
    m.z = r.float64
    m
  end
end
