# geometry_msgs/msg/WrenchStamped (ROS 2 jazzy), generated by asterism_msggen.rb from
# WrenchStamped.msg. Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Wrench")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::GeometryMsgs
end

class ::Asterism::ROS::GeometryMsgs::WrenchStamped < ::Asterism::ROS::Message
  ROS_NAME = "geometry_msgs/msg/WrenchStamped"
  TYPE_NAME = "geometry_msgs::msg::dds_::WrenchStamped_"
  TYPE_HASH = "RIHS01_8dc3deaf06b2ab281f9f9a742a8961c328ca7cec16e3fd6586d3a5c83fa78f77"
  FIELDS = [:header, :wrench]

  attr_accessor :header, :wrench

  def initialize(header: nil, wrench: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @wrench = ::Asterism::ROS::GeometryMsgs::Wrench.from(wrench)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::GeometryMsgs::Wrench.write(w, ::Asterism::ROS::GeometryMsgs::Wrench.from(m.wrench))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.wrench = ::Asterism::ROS::GeometryMsgs::Wrench.read(r)
    m
  end
end
