# nav_msgs/msg/MapMetaData (ROS 2 jazzy), generated by asterism_msggen.rb from
# MapMetaData.msg of the package nav_msgs.
# License: Apache License 2.0, as the definition (package.xml of nav_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("builtin_interfaces/msg/Time")
::Asterism::ROS.require_type("geometry_msgs/msg/Pose")

module ::Asterism::ROS::NavMsgs
end

class ::Asterism::ROS::NavMsgs::MapMetaData < ::Asterism::ROS::Message
  ROS_NAME = "nav_msgs/msg/MapMetaData"
  TYPE_NAME = "nav_msgs::msg::dds_::MapMetaData_"
  TYPE_HASH = "RIHS01_2772d4b2000ef2b35dbaeb80fd3946c1369f817fb4f75677d916d27c17d763c8"
  FIELDS = [:map_load_time, :resolution, :width, :height, :origin]
  FIELD_TYPES = [
    ["map_load_time", "builtin_interfaces/msg/Time", "scalar", "builtin_interfaces/msg/Time", nil, nil],
    ["resolution", "float32", "scalar", nil, nil, nil],
    ["width", "uint32", "scalar", nil, nil, nil],
    ["height", "uint32", "scalar", nil, nil, nil],
    ["origin", "geometry_msgs/msg/Pose", "scalar", "geometry_msgs/msg/Pose", nil, nil]
  ]

  attr_accessor :map_load_time, :resolution, :width, :height, :origin

  def initialize(map_load_time: nil, resolution: nil, width: nil, height: nil, origin: nil)
    @map_load_time = ::Asterism::ROS::BuiltinInterfaces::Time.from(map_load_time)
    @resolution = resolution.nil? ? 0.0 : resolution
    @width = width.nil? ? 0 : width
    @height = height.nil? ? 0 : height
    @origin = ::Asterism::ROS::GeometryMsgs::Pose.from(origin)
  end

  def self.write(w, m)
    ::Asterism::ROS::BuiltinInterfaces::Time.write(w, ::Asterism::ROS::BuiltinInterfaces::Time.from(m.map_load_time))
    w.float32(m.resolution)
    w.uint32(m.width)
    w.uint32(m.height)
    ::Asterism::ROS::GeometryMsgs::Pose.write(w, ::Asterism::ROS::GeometryMsgs::Pose.from(m.origin))
  end

  def self.read(r)
    m = new
    m.map_load_time = ::Asterism::ROS::BuiltinInterfaces::Time.read(r)
    m.resolution = r.float32
    m.width = r.uint32
    m.height = r.uint32
    m.origin = ::Asterism::ROS::GeometryMsgs::Pose.read(r)
    m
  end
end
