# nav_msgs/msg/OccupancyGrid (ROS 2 jazzy), generated by asterism_msggen.rb from
# OccupancyGrid.msg of the package nav_msgs.
# License: Apache License 2.0, as the definition (package.xml of nav_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("nav_msgs/msg/MapMetaData")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::NavMsgs
end

class ::Asterism::ROS::NavMsgs::OccupancyGrid < ::Asterism::ROS::Message
  ROS_NAME = "nav_msgs/msg/OccupancyGrid"
  TYPE_NAME = "nav_msgs::msg::dds_::OccupancyGrid_"
  TYPE_HASH = "RIHS01_8d348150c12913a31ee0ec170fbf25089e4745d17035792a1ba94d6f0bc0cfc7"
  FIELDS = [:header, :info, :data]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["info", "nav_msgs/msg/MapMetaData", "scalar", "nav_msgs/msg/MapMetaData", nil, nil],
    ["data", "int8", "sequence", nil, nil, nil]
  ]

  attr_accessor :header, :info, :data

  def initialize(header: nil, info: nil, data: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @info = ::Asterism::ROS::NavMsgs::MapMetaData.from(info)
    @data = data.nil? ? [] : data
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::NavMsgs::MapMetaData.write(w, ::Asterism::ROS::NavMsgs::MapMetaData.from(m.info))
    w.array(:int8, m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.info = ::Asterism::ROS::NavMsgs::MapMetaData.read(r)
    m.data = r.array(:int8, nil)
    m
  end
end
