# nav_msgs/msg/Odometry (ROS 2 jazzy), generated by asterism_msggen.rb from
# Odometry.msg of the package nav_msgs.
# License: Apache License 2.0, as the definition (package.xml of nav_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/PoseWithCovariance")
::Asterism::ROS.require_type("geometry_msgs/msg/TwistWithCovariance")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::NavMsgs
end

class ::Asterism::ROS::NavMsgs::Odometry < ::Asterism::ROS::Message
  ROS_NAME = "nav_msgs/msg/Odometry"
  TYPE_NAME = "nav_msgs::msg::dds_::Odometry_"
  TYPE_HASH = "RIHS01_3cc97dc7fb7502f8714462c526d369e35b603cfc34d946e3f2eda2766dfec6e0"
  FIELDS = [:header, :child_frame_id, :pose, :twist]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["child_frame_id", "string", "scalar", nil, nil, nil],
    ["pose", "geometry_msgs/msg/PoseWithCovariance", "scalar", "geometry_msgs/msg/PoseWithCovariance", nil, nil],
    ["twist", "geometry_msgs/msg/TwistWithCovariance", "scalar", "geometry_msgs/msg/TwistWithCovariance", nil, nil]
  ]

  attr_accessor :header, :child_frame_id, :pose, :twist

  def initialize(header: nil, child_frame_id: nil, pose: nil, twist: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @child_frame_id = child_frame_id.nil? ? "" : child_frame_id
    @pose = ::Asterism::ROS::GeometryMsgs::PoseWithCovariance.from(pose)
    @twist = ::Asterism::ROS::GeometryMsgs::TwistWithCovariance.from(twist)
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.string(m.child_frame_id)
    ::Asterism::ROS::GeometryMsgs::PoseWithCovariance.write(w, ::Asterism::ROS::GeometryMsgs::PoseWithCovariance.from(m.pose))
    ::Asterism::ROS::GeometryMsgs::TwistWithCovariance.write(w, ::Asterism::ROS::GeometryMsgs::TwistWithCovariance.from(m.twist))
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.child_frame_id = r.string
    m.pose = ::Asterism::ROS::GeometryMsgs::PoseWithCovariance.read(r)
    m.twist = ::Asterism::ROS::GeometryMsgs::TwistWithCovariance.read(r)
    m
  end
end
