# nav_msgs/msg/Path (ROS 2 jazzy), generated by asterism_msggen.rb from
# Path.msg of the package nav_msgs.
# License: Apache License 2.0, as the definition (package.xml of nav_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/PoseStamped")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::NavMsgs
end

class ::Asterism::ROS::NavMsgs::Path < ::Asterism::ROS::Message
  ROS_NAME = "nav_msgs/msg/Path"
  TYPE_NAME = "nav_msgs::msg::dds_::Path_"
  TYPE_HASH = "RIHS01_1957a5bb3cee5da65c4e52e52b65a93df227efce4c20f8458b36e73066ca334b"
  FIELDS = [:header, :poses]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["poses", "geometry_msgs/msg/PoseStamped", "sequence", "geometry_msgs/msg/PoseStamped", nil, nil]
  ]

  attr_accessor :header, :poses

  def initialize(header: nil, poses: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @poses = poses.nil? ? [] : poses.map { |e| ::Asterism::ROS::GeometryMsgs::PoseStamped.from(e) }
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.structs(::Asterism::ROS::GeometryMsgs::PoseStamped, m.poses, nil, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.poses = r.structs(::Asterism::ROS::GeometryMsgs::PoseStamped, nil)
    m
  end
end
