# Make lib/mujoco/layout_<version>.rb: where the fields this example reads
# sit in MuJoCo's mjModel and mjData, taken from the pinned release's own
# headers (vendor/mujoco-<tag>/include) by compiling a small C program with
# offsetof() and running it. Nothing is guessed or counted by hand.
#
#   ruby examples/mujoco/fetch.rb && ruby examples/mujoco/layout_gen.rb
#
# Needs a C compiler (cc) once, when MuJoCo is updated; running the example
# does not (the generated file is committed).
require "fileutils"
require "open3"
require "tmpdir"

DIR = __dir__

pin = File.readlines(File.join(DIR, "MUJOCO_PIN"), chomp: true)
          .reject { |l| l.start_with?("#") || l.strip.empty? }
          .to_h { |l| l.split(/:\s*/, 2) }
tag = pin["tag"]
inc = File.join(DIR, "vendor", "mujoco-#{tag}", "include")
abort "layout_gen.rb: #{inc} not found; run fetch.rb first" unless File.directory?(inc)

# [struct, field (a C member designator), kind]
#   size: mjtSize (int64)   num: mjtNum (double)
#   num_ptr: mjtNum*        int_ptr: int*
FIELDS = [
  ["mjModel", "nq", :size], ["mjModel", "nv", :size], ["mjModel", "nu", :size],
  ["mjModel", "nbody", :size], ["mjModel", "njnt", :size], ["mjModel", "ngeom", :size],
  ["mjModel", "nsite", :size], ["mjModel", "nsensor", :size], ["mjModel", "nsensordata", :size],
  ["mjModel", "opt.timestep", :num],
  ["mjModel", "jnt_type", :int_ptr], ["mjModel", "jnt_qposadr", :int_ptr], ["mjModel", "jnt_dofadr", :int_ptr],
  ["mjModel", "geom_type", :int_ptr], ["mjModel", "geom_size", :num_ptr],
  ["mjModel", "sensor_dim", :int_ptr], ["mjModel", "sensor_adr", :int_ptr],
  ["mjData", "time", :num],
  ["mjData", "qpos", :num_ptr], ["mjData", "qvel", :num_ptr], ["mjData", "ctrl", :num_ptr],
  ["mjData", "sensordata", :num_ptr],
  ["mjData", "xpos", :num_ptr], ["mjData", "xquat", :num_ptr],
  ["mjData", "geom_xpos", :num_ptr], ["mjData", "geom_xmat", :num_ptr]
].freeze

# The C type each kind must be: checked by the compiler, so a field whose
# type changed in a later release fails here instead of being misread.
CTYPE = { size: "mjtSize", num: "mjtNum", num_ptr: "mjtNum*", int_ptr: "int*" }.freeze

OBJS = %w[BODY JOINT GEOM SITE ACTUATOR SENSOR].freeze
JOINTS = %w[FREE BALL SLIDE HINGE].freeze
GEOMS = %w[PLANE SPHERE CAPSULE ELLIPSOID CYLINDER BOX].freeze

src = +<<~C
  #include <stdio.h>
  #include <stddef.h>
  #include <mujoco/mujoco.h>
  #define CHECK(s, f, t) _Static_assert(__builtin_types_compatible_p(__typeof__(((s*)0)->f), t), #s "." #f " is not " #t)
C
FIELDS.each { |s, f, k| src << "CHECK(#{s}, #{f}, #{CTYPE[k]});\n" }
src << "_Static_assert(sizeof(mjtNum) == 8, \"mjtNum is not double\");\n"
src << "_Static_assert(sizeof(int) == 4, \"int is not 32 bit\");\n"
src << "_Static_assert(sizeof(void*) == 8, \"not a 64-bit build\");\n"
src << "int main(void) {\n"
src << "  printf(\"header_version %d\\n\", mjVERSION_HEADER);\n"
src << "  printf(\"sizeof mjModel %zu\\n\", sizeof(mjModel));\n"
src << "  printf(\"sizeof mjData %zu\\n\", sizeof(mjData));\n"
FIELDS.each { |s, f, _| src << "  printf(\"off #{s} #{f} %zu\\n\", offsetof(#{s}, #{f}));\n" }
OBJS.each { |o| src << "  printf(\"enum OBJ #{o} %d\\n\", (int)mjOBJ_#{o});\n" }
JOINTS.each { |o| src << "  printf(\"enum JNT #{o} %d\\n\", (int)mjJNT_#{o});\n" }
GEOMS.each { |o| src << "  printf(\"enum GEOM #{o} %d\\n\", (int)mjGEOM_#{o});\n" }
src << "  return 0;\n}\n"

out = Dir.mktmpdir do |tmp|
  c = File.join(tmp, "layout.c")
  exe = File.join(tmp, "layout")
  File.write(c, src)
  _o, err, st = Open3.capture3("cc", "-std=c11", "-I", inc, "-o", exe, c)
  abort "layout_gen.rb: cc failed:\n#{err}" unless st.success?
  o, err, st = Open3.capture3(exe)
  abort "layout_gen.rb: #{err}" unless st.success?
  o
end

vals = { off: {}, enum: Hash.new { |h, k| h[k] = {} } }
out.each_line do |l|
  w = l.split
  case w[0]
  when "header_version" then vals[:header] = Integer(w[1])
  when "sizeof" then vals[w[1]] = Integer(w[2])
  when "off" then vals[:off][[w[1], w[2]]] = Integer(w[3])
  when "enum" then vals[:enum][w[1]][w[2]] = Integer(w[3])
  end
end
want = Integer(pin["header_version"])
abort "layout_gen.rb: headers say #{vals[:header]}, MUJOCO_PIN says #{want}" unless vals[:header] == want

name = "layout_#{tag.tr('.', '_')}.rb"
def table(vals, struct)
  FIELDS.select { |s, _, _| s == struct }.map do |_, f, k|
    format("      %-14s [%5d, :%s]", "#{f.tr('.', '_')}:", vals[:off][[struct, f]], k)
  end.join(",\n")
end

def enum(h) = h.map { |k, v| "#{k.downcase}: #{v}" }.join(", ")

File.write(File.join(DIR, "lib", "mujoco", name), <<~RUBY)
  # Generated by examples/mujoco/layout_gen.rb from the headers of MuJoCo
  # #{tag} (#{pin['asset.x86_64-linux']}); do not edit. Offsets in bytes of the
  # fields this example reads, with their C types:
  #   size: mjtSize (int64)  num: mjtNum (double)  num_ptr: mjtNum*  int_ptr: int*
  # The types were checked by the compiler (layout_gen.rb), the version by
  # MuJoCo::Lib.open against mj_version() of the library it loads.
  module MuJoCo
    module Layout
      VERSION = "#{tag}"
      HEADER_VERSION = #{vals[:header]}
      SIZEOF_MODEL = #{vals['mjModel']}
      SIZEOF_DATA = #{vals['mjData']}
      MODEL = {
  #{table(vals, 'mjModel')}
      }.freeze
      DATA = {
  #{table(vals, 'mjData')}
      }.freeze
      OBJ = { #{enum(vals[:enum]['OBJ'])} }.freeze
      JNT = { #{enum(vals[:enum]['JNT'])} }.freeze
      GEOM = { #{enum(vals[:enum]['GEOM'])} }.freeze
    end
  end
RUBY
puts "wrote lib/mujoco/#{name} (mjModel #{vals['mjModel']} B, mjData #{vals['mjData']} B)"
