# sensor_msgs/msg/Imu (ROS 2 jazzy), generated by asterism_msggen.rb from
# Imu.msg. Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/Quaternion")
::Asterism::ROS.require_type("geometry_msgs/msg/Vector3")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::Imu < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/Imu"
  TYPE_NAME = "sensor_msgs::msg::dds_::Imu_"
  TYPE_HASH = "RIHS01_7d9a00ff131080897a5ec7e26e315954b8eae3353c3f995c55faf71574000b5b"
  FIELDS = [:header, :orientation, :orientation_covariance, :angular_velocity, :angular_velocity_covariance, :linear_acceleration, :linear_acceleration_covariance]

  attr_accessor :header, :orientation, :orientation_covariance, :angular_velocity, :angular_velocity_covariance, :linear_acceleration, :linear_acceleration_covariance

  def initialize(header: nil, orientation: nil, orientation_covariance: nil, angular_velocity: nil, angular_velocity_covariance: nil, linear_acceleration: nil, linear_acceleration_covariance: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @orientation = ::Asterism::ROS::GeometryMsgs::Quaternion.from(orientation)
    @orientation_covariance = orientation_covariance.nil? ? ::Array.new(9, 0.0) : orientation_covariance
    @angular_velocity = ::Asterism::ROS::GeometryMsgs::Vector3.from(angular_velocity)
    @angular_velocity_covariance = angular_velocity_covariance.nil? ? ::Array.new(9, 0.0) : angular_velocity_covariance
    @linear_acceleration = ::Asterism::ROS::GeometryMsgs::Vector3.from(linear_acceleration)
    @linear_acceleration_covariance = linear_acceleration_covariance.nil? ? ::Array.new(9, 0.0) : linear_acceleration_covariance
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::GeometryMsgs::Quaternion.write(w, ::Asterism::ROS::GeometryMsgs::Quaternion.from(m.orientation))
    w.array(:float64, m.orientation_covariance, 9, nil)
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.angular_velocity))
    w.array(:float64, m.angular_velocity_covariance, 9, nil)
    ::Asterism::ROS::GeometryMsgs::Vector3.write(w, ::Asterism::ROS::GeometryMsgs::Vector3.from(m.linear_acceleration))
    w.array(:float64, m.linear_acceleration_covariance, 9, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.orientation = ::Asterism::ROS::GeometryMsgs::Quaternion.read(r)
    m.orientation_covariance = r.array(:float64, 9)
    m.angular_velocity = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m.angular_velocity_covariance = r.array(:float64, 9)
    m.linear_acceleration = ::Asterism::ROS::GeometryMsgs::Vector3.read(r)
    m.linear_acceleration_covariance = r.array(:float64, 9)
    m
  end
end
