# sensor_msgs/msg/NavSatStatus (ROS 2 jazzy), generated by asterism_msggen.rb from
# NavSatStatus.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::NavSatStatus < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/NavSatStatus"
  TYPE_NAME = "sensor_msgs::msg::dds_::NavSatStatus_"
  TYPE_HASH = "RIHS01_d1ed3befa628e09571bd273b888ba1c1fd187c9a5e0006b385d7e5e9095a3204"
  FIELDS = [:status, :service]
  STATUS_UNKNOWN = -2
  STATUS_NO_FIX = -1
  STATUS_FIX = 0
  STATUS_SBAS_FIX = 1
  STATUS_GBAS_FIX = 2
  SERVICE_UNKNOWN = 0
  SERVICE_GPS = 1
  SERVICE_GLONASS = 2
  SERVICE_COMPASS = 4
  SERVICE_GALILEO = 8

  attr_accessor :status, :service

  def initialize(status: nil, service: nil)
    @status = status.nil? ? -2 : status
    @service = service.nil? ? 0 : service
  end

  def self.write(w, m)
    w.int8(m.status)
    w.uint16(m.service)
  end

  def self.read(r)
    m = new
    m.status = r.int8
    m.service = r.uint16
    m
  end
end
