# sensor_msgs/msg/CompressedImage (ROS 2 jazzy), generated by asterism_msggen.rb from
# CompressedImage.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::CompressedImage < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/CompressedImage"
  TYPE_NAME = "sensor_msgs::msg::dds_::CompressedImage_"
  TYPE_HASH = "RIHS01_15640771531571185e2efc8a100baf923961a4d15d5569652e6cb6691e8e371a"
  FIELDS = [:header, :format, :data]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["format", "string", "scalar", nil, nil, nil],
    ["data", "uint8", "sequence", nil, nil, nil]
  ]

  attr_accessor :header, :format, :data

  def initialize(header: nil, format: nil, data: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @format = format.nil? ? "" : format
    @data = data.nil? ? "" : data
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.string(m.format)
    w.bytes(m.data, nil, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.format = r.string
    m.data = r.bytes(nil)
    m
  end
end
