# sensor_msgs/msg/JointState (ROS 2 jazzy), generated by asterism_msggen.rb from
# JointState.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::JointState < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/JointState"
  TYPE_NAME = "sensor_msgs::msg::dds_::JointState_"
  TYPE_HASH = "RIHS01_a13ee3a330e346c9d87b5aa18d24e11690752bd33a0350f11c5882bc9179260e"
  FIELDS = [:header, :name, :position, :velocity, :effort]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["name", "string", "sequence", nil, nil, nil],
    ["position", "float64", "sequence", nil, nil, nil],
    ["velocity", "float64", "sequence", nil, nil, nil],
    ["effort", "float64", "sequence", nil, nil, nil]
  ]

  attr_accessor :header, :name, :position, :velocity, :effort

  def initialize(header: nil, name: nil, position: nil, velocity: nil, effort: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @name = name.nil? ? [] : name
    @position = position.nil? ? [] : position
    @velocity = velocity.nil? ? [] : velocity
    @effort = effort.nil? ? [] : effort
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.array(:string, m.name, nil, nil, nil)
    w.array(:float64, m.position, nil, nil)
    w.array(:float64, m.velocity, nil, nil)
    w.array(:float64, m.effort, nil, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.name = r.array(:string, nil)
    m.position = r.array(:float64, nil)
    m.velocity = r.array(:float64, nil)
    m.effort = r.array(:float64, nil)
    m
  end
end
