# sensor_msgs/msg/LaserScan (ROS 2 jazzy), generated by asterism_msggen.rb from
# LaserScan.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::LaserScan < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/LaserScan"
  TYPE_NAME = "sensor_msgs::msg::dds_::LaserScan_"
  TYPE_HASH = "RIHS01_64c191398013af96509d518dac71d5164f9382553fce5c1f8cca5be7924bd828"
  FIELDS = [:header, :angle_min, :angle_max, :angle_increment, :time_increment, :scan_time, :range_min, :range_max, :ranges, :intensities]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["angle_min", "float32", "scalar", nil, nil, nil],
    ["angle_max", "float32", "scalar", nil, nil, nil],
    ["angle_increment", "float32", "scalar", nil, nil, nil],
    ["time_increment", "float32", "scalar", nil, nil, nil],
    ["scan_time", "float32", "scalar", nil, nil, nil],
    ["range_min", "float32", "scalar", nil, nil, nil],
    ["range_max", "float32", "scalar", nil, nil, nil],
    ["ranges", "float32", "sequence", nil, nil, nil],
    ["intensities", "float32", "sequence", nil, nil, nil]
  ]

  attr_accessor :header, :angle_min, :angle_max, :angle_increment, :time_increment, :scan_time, :range_min, :range_max, :ranges, :intensities

  def initialize(header: nil, angle_min: nil, angle_max: nil, angle_increment: nil, time_increment: nil, scan_time: nil, range_min: nil, range_max: nil, ranges: nil, intensities: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @angle_min = angle_min.nil? ? 0.0 : angle_min
    @angle_max = angle_max.nil? ? 0.0 : angle_max
    @angle_increment = angle_increment.nil? ? 0.0 : angle_increment
    @time_increment = time_increment.nil? ? 0.0 : time_increment
    @scan_time = scan_time.nil? ? 0.0 : scan_time
    @range_min = range_min.nil? ? 0.0 : range_min
    @range_max = range_max.nil? ? 0.0 : range_max
    @ranges = ranges.nil? ? [] : ranges
    @intensities = intensities.nil? ? [] : intensities
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.float32(m.angle_min)
    w.float32(m.angle_max)
    w.float32(m.angle_increment)
    w.float32(m.time_increment)
    w.float32(m.scan_time)
    w.float32(m.range_min)
    w.float32(m.range_max)
    w.array(:float32, m.ranges, nil, nil)
    w.array(:float32, m.intensities, nil, nil)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.angle_min = r.float32
    m.angle_max = r.float32
    m.angle_increment = r.float32
    m.time_increment = r.float32
    m.scan_time = r.float32
    m.range_min = r.float32
    m.range_max = r.float32
    m.ranges = r.array(:float32, nil)
    m.intensities = r.array(:float32, nil)
    m
  end
end
