# sensor_msgs/msg/NavSatFix (ROS 2 jazzy), generated by asterism_msggen.rb from
# NavSatFix.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("sensor_msgs/msg/NavSatStatus")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::NavSatFix < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/NavSatFix"
  TYPE_NAME = "sensor_msgs::msg::dds_::NavSatFix_"
  TYPE_HASH = "RIHS01_62223ab3fe210a15976021da7afddc9e200dc9ec75231c1b6a557fc598a65404"
  FIELDS = [:header, :status, :latitude, :longitude, :altitude, :position_covariance, :position_covariance_type]
  COVARIANCE_TYPE_UNKNOWN = 0
  COVARIANCE_TYPE_APPROXIMATED = 1
  COVARIANCE_TYPE_DIAGONAL_KNOWN = 2
  COVARIANCE_TYPE_KNOWN = 3

  attr_accessor :header, :status, :latitude, :longitude, :altitude, :position_covariance, :position_covariance_type

  def initialize(header: nil, status: nil, latitude: nil, longitude: nil, altitude: nil, position_covariance: nil, position_covariance_type: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @status = ::Asterism::ROS::SensorMsgs::NavSatStatus.from(status)
    @latitude = latitude.nil? ? 0.0 : latitude
    @longitude = longitude.nil? ? 0.0 : longitude
    @altitude = altitude.nil? ? 0.0 : altitude
    @position_covariance = position_covariance.nil? ? ::Array.new(9, 0.0) : position_covariance
    @position_covariance_type = position_covariance_type.nil? ? 0 : position_covariance_type
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    ::Asterism::ROS::SensorMsgs::NavSatStatus.write(w, ::Asterism::ROS::SensorMsgs::NavSatStatus.from(m.status))
    w.float64(m.latitude)
    w.float64(m.longitude)
    w.float64(m.altitude)
    w.array(:float64, m.position_covariance, 9, nil)
    w.uint8(m.position_covariance_type)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.status = ::Asterism::ROS::SensorMsgs::NavSatStatus.read(r)
    m.latitude = r.float64
    m.longitude = r.float64
    m.altitude = r.float64
    m.position_covariance = r.array(:float64, 9)
    m.position_covariance_type = r.uint8
    m
  end
end
