# sensor_msgs/msg/PointField (ROS 2 jazzy), generated by asterism_msggen.rb from
# PointField.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::PointField < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/PointField"
  TYPE_NAME = "sensor_msgs::msg::dds_::PointField_"
  TYPE_HASH = "RIHS01_5c6a4750728c2bcfbbf7037225b20b02d4429634732146b742dee1726637ef01"
  FIELDS = [:name, :offset, :datatype, :count]
  FIELD_TYPES = [
    ["name", "string", "scalar", nil, nil, nil],
    ["offset", "uint32", "scalar", nil, nil, nil],
    ["datatype", "uint8", "scalar", nil, nil, nil],
    ["count", "uint32", "scalar", nil, nil, nil]
  ]
  INT8 = 1
  UINT8 = 2
  INT16 = 3
  UINT16 = 4
  INT32 = 5
  UINT32 = 6
  FLOAT32 = 7
  FLOAT64 = 8

  attr_accessor :name, :offset, :datatype, :count

  def initialize(name: nil, offset: nil, datatype: nil, count: nil)
    @name = name.nil? ? "" : name
    @offset = offset.nil? ? 0 : offset
    @datatype = datatype.nil? ? 0 : datatype
    @count = count.nil? ? 0 : count
  end

  def self.write(w, m)
    w.string(m.name)
    w.uint32(m.offset)
    w.uint8(m.datatype)
    w.uint32(m.count)
  end

  def self.read(r)
    m = new
    m.name = r.string
    m.offset = r.uint32
    m.datatype = r.uint8
    m.count = r.uint32
    m
  end
end
