# sensor_msgs/msg/PointCloud2 (ROS 2 jazzy), generated by asterism_msggen.rb from
# PointCloud2.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("sensor_msgs/msg/PointField")
::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::PointCloud2 < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/PointCloud2"
  TYPE_NAME = "sensor_msgs::msg::dds_::PointCloud2_"
  TYPE_HASH = "RIHS01_9198cabf7da3796ae6fe19c4cb3bdd3525492988c70522628af5daa124bae2b5"
  FIELDS = [:header, :height, :width, :fields, :is_bigendian, :point_step, :row_step, :data, :is_dense]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["height", "uint32", "scalar", nil, nil, nil],
    ["width", "uint32", "scalar", nil, nil, nil],
    ["fields", "sensor_msgs/msg/PointField", "sequence", "sensor_msgs/msg/PointField", nil, nil],
    ["is_bigendian", "bool", "scalar", nil, nil, nil],
    ["point_step", "uint32", "scalar", nil, nil, nil],
    ["row_step", "uint32", "scalar", nil, nil, nil],
    ["data", "uint8", "sequence", nil, nil, nil],
    ["is_dense", "bool", "scalar", nil, nil, nil]
  ]

  attr_accessor :header, :height, :width, :fields, :is_bigendian, :point_step, :row_step, :data, :is_dense

  def initialize(header: nil, height: nil, width: nil, fields: nil, is_bigendian: nil, point_step: nil, row_step: nil, data: nil, is_dense: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @height = height.nil? ? 0 : height
    @width = width.nil? ? 0 : width
    @fields = fields.nil? ? [] : fields.map { |e| ::Asterism::ROS::SensorMsgs::PointField.from(e) }
    @is_bigendian = is_bigendian.nil? ? false : is_bigendian
    @point_step = point_step.nil? ? 0 : point_step
    @row_step = row_step.nil? ? 0 : row_step
    @data = data.nil? ? "" : data
    @is_dense = is_dense.nil? ? false : is_dense
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.uint32(m.height)
    w.uint32(m.width)
    w.structs(::Asterism::ROS::SensorMsgs::PointField, m.fields, nil, nil)
    w.bool(m.is_bigendian)
    w.uint32(m.point_step)
    w.uint32(m.row_step)
    w.bytes(m.data, nil, nil)
    w.bool(m.is_dense)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.height = r.uint32
    m.width = r.uint32
    m.fields = r.structs(::Asterism::ROS::SensorMsgs::PointField, nil)
    m.is_bigendian = r.bool
    m.point_step = r.uint32
    m.row_step = r.uint32
    m.data = r.bytes(nil)
    m.is_dense = r.bool
    m
  end
end
