# sensor_msgs/msg/Range (ROS 2 jazzy), generated by asterism_msggen.rb from
# Range.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::Range < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/Range"
  TYPE_NAME = "sensor_msgs::msg::dds_::Range_"
  TYPE_HASH = "RIHS01_b42b62562e93cbfe9d42b82fe5994dfa3d63d7d5c90a317981703f7388adff3a"
  FIELDS = [:header, :radiation_type, :field_of_view, :min_range, :max_range, :range, :variance]
  ULTRASOUND = 0
  INFRARED = 1

  attr_accessor :header, :radiation_type, :field_of_view, :min_range, :max_range, :range, :variance

  def initialize(header: nil, radiation_type: nil, field_of_view: nil, min_range: nil, max_range: nil, range: nil, variance: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @radiation_type = radiation_type.nil? ? 0 : radiation_type
    @field_of_view = field_of_view.nil? ? 0.0 : field_of_view
    @min_range = min_range.nil? ? 0.0 : min_range
    @max_range = max_range.nil? ? 0.0 : max_range
    @range = range.nil? ? 0.0 : range
    @variance = variance.nil? ? 0.0 : variance
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.uint8(m.radiation_type)
    w.float32(m.field_of_view)
    w.float32(m.min_range)
    w.float32(m.max_range)
    w.float32(m.range)
    w.float32(m.variance)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.radiation_type = r.uint8
    m.field_of_view = r.float32
    m.min_range = r.float32
    m.max_range = r.float32
    m.range = r.float32
    m.variance = r.float32
    m
  end
end
