# sensor_msgs/msg/RelativeHumidity (ROS 2 jazzy), generated by asterism_msggen.rb from
# RelativeHumidity.msg. Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::RelativeHumidity < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/RelativeHumidity"
  TYPE_NAME = "sensor_msgs::msg::dds_::RelativeHumidity_"
  TYPE_HASH = "RIHS01_8687c99b4fb393cb2e545e407b5ea7fd0b5d8960bcd849a0f86c544740138839"
  FIELDS = [:header, :relative_humidity, :variance]

  attr_accessor :header, :relative_humidity, :variance

  def initialize(header: nil, relative_humidity: nil, variance: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @relative_humidity = relative_humidity.nil? ? 0.0 : relative_humidity
    @variance = variance.nil? ? 0.0 : variance
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.float64(m.relative_humidity)
    w.float64(m.variance)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.relative_humidity = r.float64
    m.variance = r.float64
    m
  end
end
