# sensor_msgs/msg/Temperature (ROS 2 jazzy), generated by asterism_msggen.rb from
# Temperature.msg of the package sensor_msgs.
# License: Apache License 2.0, as the definition (package.xml of sensor_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("std_msgs/msg/Header")

module ::Asterism::ROS::SensorMsgs
end

class ::Asterism::ROS::SensorMsgs::Temperature < ::Asterism::ROS::Message
  ROS_NAME = "sensor_msgs/msg/Temperature"
  TYPE_NAME = "sensor_msgs::msg::dds_::Temperature_"
  TYPE_HASH = "RIHS01_72514a14126ab9f8a9abec974c78e5610a367b59db5da355ff1fb982d5bad4b8"
  FIELDS = [:header, :temperature, :variance]
  FIELD_TYPES = [
    ["header", "std_msgs/msg/Header", "scalar", "std_msgs/msg/Header", nil, nil],
    ["temperature", "float64", "scalar", nil, nil, nil],
    ["variance", "float64", "scalar", nil, nil, nil]
  ]

  attr_accessor :header, :temperature, :variance

  def initialize(header: nil, temperature: nil, variance: nil)
    @header = ::Asterism::ROS::StdMsgs::Header.from(header)
    @temperature = temperature.nil? ? 0.0 : temperature
    @variance = variance.nil? ? 0.0 : variance
  end

  def self.write(w, m)
    ::Asterism::ROS::StdMsgs::Header.write(w, ::Asterism::ROS::StdMsgs::Header.from(m.header))
    w.float64(m.temperature)
    w.float64(m.variance)
  end

  def self.read(r)
    m = new
    m.header = ::Asterism::ROS::StdMsgs::Header.read(r)
    m.temperature = r.float64
    m.variance = r.float64
    m
  end
end
