# Generated by examples/mujoco/layout_gen.rb from the headers of MuJoCo
# 3.15.0 (mujoco-3.15.0-linux-x86_64.tar.gz); do not edit. Offsets in bytes of the
# fields this example reads, with their C types:
#   size: mjtSize (int64)  num: mjtNum (double)  num_ptr: mjtNum*  int_ptr: int*
# The types were checked by the compiler (layout_gen.rb), the version by
# MuJoCo::Lib.open against mj_version() of the library it loads.
module MuJoCo
  module Layout
    VERSION = "3.15.0"
    HEADER_VERSION = 3015000
    SIZEOF_MODEL = 5656
    SIZEOF_DATA = 162104
    MODEL = {
      nq:            [    0, :size],
      nv:            [    8, :size],
      nu:            [   16, :size],
      nbody:         [   48, :size],
      njnt:          [   88, :size],
      ngeom:         [  136, :size],
      nsite:         [  144, :size],
      nsensor:       [  496, :size],
      nsensordata:   [  736, :size],
      opt_timestep:  [  784, :num],
      jnt_type:      [ 2096, :int_ptr],
      jnt_qposadr:   [ 2104, :int_ptr],
      jnt_dofadr:    [ 2112, :int_ptr],
      geom_type:     [ 2408, :int_ptr],
      geom_size:     [ 2520, :num_ptr],
      sensor_dim:    [ 5072, :int_ptr],
      sensor_adr:    [ 5080, :int_ptr]
    }.freeze
    DATA = {
      time:          [160648, :num],
      qpos:          [160688, :num_ptr],
      qvel:          [160696, :num_ptr],
      ctrl:          [160736, :num_ptr],
      sensordata:    [160808, :num_ptr],
      xpos:          [160840, :num_ptr],
      xquat:         [160848, :num_ptr],
      geom_xpos:     [160896, :num_ptr],
      geom_xmat:     [160904, :num_ptr]
    }.freeze
    OBJ = { body: 1, joint: 3, geom: 5, site: 6, actuator: 19, sensor: 20 }.freeze
    JNT = { free: 0, ball: 1, slide: 2, hinge: 3 }.freeze
    GEOM = { plane: 0, sphere: 2, capsule: 3, ellipsoid: 4, cylinder: 5, box: 6 }.freeze
  end
end
