# tf2_msgs/msg/TFMessage (ROS 2 jazzy), generated by asterism_msggen.rb from
# TFMessage.msg of the package tf2_msgs.
# License: BSD, as the definition (package.xml of tf2_msgs).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("geometry_msgs/msg/TransformStamped")

module ::Asterism::ROS::Tf2Msgs
end

class ::Asterism::ROS::Tf2Msgs::TFMessage < ::Asterism::ROS::Message
  ROS_NAME = "tf2_msgs/msg/TFMessage"
  TYPE_NAME = "tf2_msgs::msg::dds_::TFMessage_"
  TYPE_HASH = "RIHS01_e369d0f05a23ae52508854b66f6aa0437f3449d652e8cbf22d5abe85d020f087"
  FIELDS = [:transforms]
  FIELD_TYPES = [
    ["transforms", "geometry_msgs/msg/TransformStamped", "sequence", "geometry_msgs/msg/TransformStamped", nil, nil]
  ]

  attr_accessor :transforms

  def initialize(transforms: nil)
    @transforms = transforms.nil? ? [] : transforms.map { |e| ::Asterism::ROS::GeometryMsgs::TransformStamped.from(e) }
  end

  def self.write(w, m)
    w.structs(::Asterism::ROS::GeometryMsgs::TransformStamped, m.transforms, nil, nil)
  end

  def self.read(r)
    m = new
    m.transforms = r.structs(::Asterism::ROS::GeometryMsgs::TransformStamped, nil)
    m
  end
end
