# rcl_interfaces/msg/Parameter (ROS 2 jazzy), generated by asterism_msggen.rb from
# Parameter.msg of the package rcl_interfaces.
# License: Apache License 2.0, as the definition (package.xml of rcl_interfaces).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("rcl_interfaces/msg/ParameterValue")

module ::Asterism::ROS::RclInterfaces
end

class ::Asterism::ROS::RclInterfaces::Parameter < ::Asterism::ROS::Message
  ROS_NAME = "rcl_interfaces/msg/Parameter"
  TYPE_NAME = "rcl_interfaces::msg::dds_::Parameter_"
  TYPE_HASH = "RIHS01_ddfe6442cffc462317adb5c92536a7b6dd55858c5c3e1e328165a6b73c2831af"
  FIELDS = [:name, :value]
  FIELD_TYPES = [
    ["name", "string", "scalar", nil, nil, nil],
    ["value", "rcl_interfaces/msg/ParameterValue", "scalar", "rcl_interfaces/msg/ParameterValue", nil, nil]
  ]

  attr_accessor :name, :value

  def initialize(name: nil, value: nil)
    @name = name.nil? ? "" : name
    @value = ::Asterism::ROS::RclInterfaces::ParameterValue.from(value)
  end

  def self.write(w, m)
    w.string(m.name)
    ::Asterism::ROS::RclInterfaces::ParameterValue.write(w, ::Asterism::ROS::RclInterfaces::ParameterValue.from(m.value))
  end

  def self.read(r)
    m = new
    m.name = r.string
    m.value = ::Asterism::ROS::RclInterfaces::ParameterValue.read(r)
    m
  end
end
