# rcl_interfaces/msg/ParameterEvent (ROS 2 jazzy), generated by asterism_msggen.rb from
# ParameterEvent.msg of the package rcl_interfaces.
# License: Apache License 2.0, as the definition (package.xml of rcl_interfaces).
# Do not edit; regenerate instead.

::Asterism::ROS.require_type("builtin_interfaces/msg/Time")
::Asterism::ROS.require_type("rcl_interfaces/msg/Parameter")

module ::Asterism::ROS::RclInterfaces
end

class ::Asterism::ROS::RclInterfaces::ParameterEvent < ::Asterism::ROS::Message
  ROS_NAME = "rcl_interfaces/msg/ParameterEvent"
  TYPE_NAME = "rcl_interfaces::msg::dds_::ParameterEvent_"
  TYPE_HASH = "RIHS01_043e627780fcad87a22d225bc2a037361dba713fca6a6b9f4b869a5aa0393204"
  FIELDS = [:stamp, :node, :new_parameters, :changed_parameters, :deleted_parameters]
  FIELD_TYPES = [
    ["stamp", "builtin_interfaces/msg/Time", "scalar", "builtin_interfaces/msg/Time", nil, nil],
    ["node", "string", "scalar", nil, nil, nil],
    ["new_parameters", "rcl_interfaces/msg/Parameter", "sequence", "rcl_interfaces/msg/Parameter", nil, nil],
    ["changed_parameters", "rcl_interfaces/msg/Parameter", "sequence", "rcl_interfaces/msg/Parameter", nil, nil],
    ["deleted_parameters", "rcl_interfaces/msg/Parameter", "sequence", "rcl_interfaces/msg/Parameter", nil, nil]
  ]

  attr_accessor :stamp, :node, :new_parameters, :changed_parameters, :deleted_parameters

  def initialize(stamp: nil, node: nil, new_parameters: nil, changed_parameters: nil, deleted_parameters: nil)
    @stamp = ::Asterism::ROS::BuiltinInterfaces::Time.from(stamp)
    @node = node.nil? ? "" : node
    @new_parameters = new_parameters.nil? ? [] : new_parameters.map { |e| ::Asterism::ROS::RclInterfaces::Parameter.from(e) }
    @changed_parameters = changed_parameters.nil? ? [] : changed_parameters.map { |e| ::Asterism::ROS::RclInterfaces::Parameter.from(e) }
    @deleted_parameters = deleted_parameters.nil? ? [] : deleted_parameters.map { |e| ::Asterism::ROS::RclInterfaces::Parameter.from(e) }
  end

  def self.write(w, m)
    ::Asterism::ROS::BuiltinInterfaces::Time.write(w, ::Asterism::ROS::BuiltinInterfaces::Time.from(m.stamp))
    w.string(m.node)
    w.structs(::Asterism::ROS::RclInterfaces::Parameter, m.new_parameters, nil, nil)
    w.structs(::Asterism::ROS::RclInterfaces::Parameter, m.changed_parameters, nil, nil)
    w.structs(::Asterism::ROS::RclInterfaces::Parameter, m.deleted_parameters, nil, nil)
  end

  def self.read(r)
    m = new
    m.stamp = ::Asterism::ROS::BuiltinInterfaces::Time.read(r)
    m.node = r.string
    m.new_parameters = r.structs(::Asterism::ROS::RclInterfaces::Parameter, nil)
    m.changed_parameters = r.structs(::Asterism::ROS::RclInterfaces::Parameter, nil)
    m.deleted_parameters = r.structs(::Asterism::ROS::RclInterfaces::Parameter, nil)
    m
  end
end
