# rcl_interfaces/msg/ParameterValue (ROS 2 jazzy), generated by asterism_msggen.rb from
# ParameterValue.msg of the package rcl_interfaces.
# License: Apache License 2.0, as the definition (package.xml of rcl_interfaces).
# Do not edit; regenerate instead.

module ::Asterism::ROS::RclInterfaces
end

class ::Asterism::ROS::RclInterfaces::ParameterValue < ::Asterism::ROS::Message
  ROS_NAME = "rcl_interfaces/msg/ParameterValue"
  TYPE_NAME = "rcl_interfaces::msg::dds_::ParameterValue_"
  TYPE_HASH = "RIHS01_115fc089a387e23c7ecd3525c9189c379109119d6ab82e8dfbde0fdf6a7f9b68"
  FIELDS = [:type, :bool_value, :integer_value, :double_value, :string_value, :byte_array_value, :bool_array_value, :integer_array_value, :double_array_value, :string_array_value]
  FIELD_TYPES = [
    ["type", "uint8", "scalar", nil, nil, nil],
    ["bool_value", "bool", "scalar", nil, nil, nil],
    ["integer_value", "int64", "scalar", nil, nil, nil],
    ["double_value", "float64", "scalar", nil, nil, nil],
    ["string_value", "string", "scalar", nil, nil, nil],
    ["byte_array_value", "byte", "sequence", nil, nil, nil],
    ["bool_array_value", "bool", "sequence", nil, nil, nil],
    ["integer_array_value", "int64", "sequence", nil, nil, nil],
    ["double_array_value", "float64", "sequence", nil, nil, nil],
    ["string_array_value", "string", "sequence", nil, nil, nil]
  ]

  attr_accessor :type, :bool_value, :integer_value, :double_value, :string_value, :byte_array_value, :bool_array_value, :integer_array_value, :double_array_value, :string_array_value

  def initialize(type: nil, bool_value: nil, integer_value: nil, double_value: nil, string_value: nil, byte_array_value: nil, bool_array_value: nil, integer_array_value: nil, double_array_value: nil, string_array_value: nil)
    @type = type.nil? ? 0 : type
    @bool_value = bool_value.nil? ? false : bool_value
    @integer_value = integer_value.nil? ? 0 : integer_value
    @double_value = double_value.nil? ? 0.0 : double_value
    @string_value = string_value.nil? ? "" : string_value
    @byte_array_value = byte_array_value.nil? ? "" : byte_array_value
    @bool_array_value = bool_array_value.nil? ? [] : bool_array_value
    @integer_array_value = integer_array_value.nil? ? [] : integer_array_value
    @double_array_value = double_array_value.nil? ? [] : double_array_value
    @string_array_value = string_array_value.nil? ? [] : string_array_value
  end

  def self.write(w, m)
    w.uint8(m.type)
    w.bool(m.bool_value)
    w.int64(m.integer_value)
    w.float64(m.double_value)
    w.string(m.string_value)
    w.bytes(m.byte_array_value, nil, nil)
    w.array(:bool, m.bool_array_value, nil, nil)
    w.array(:int64, m.integer_array_value, nil, nil)
    w.array(:float64, m.double_array_value, nil, nil)
    w.array(:string, m.string_array_value, nil, nil, nil)
  end

  def self.read(r)
    m = new
    m.type = r.uint8
    m.bool_value = r.bool
    m.integer_value = r.int64
    m.double_value = r.float64
    m.string_value = r.string
    m.byte_array_value = r.bytes(nil)
    m.bool_array_value = r.array(:bool, nil)
    m.integer_array_value = r.array(:int64, nil)
    m.double_array_value = r.array(:float64, nil)
    m.string_array_value = r.array(:string, nil)
    m
  end
end
