# std_msgs/msg/UInt16 (ROS 2 jazzy), generated by asterism_msggen.rb from
# UInt16.msg. Do not edit; regenerate instead.

module ::Asterism::ROS::StdMsgs
end

class ::Asterism::ROS::StdMsgs::UInt16 < ::Asterism::ROS::Message
  ROS_NAME = "std_msgs/msg/UInt16"
  TYPE_NAME = "std_msgs::msg::dds_::UInt16_"
  TYPE_HASH = "RIHS01_08a406e4b022bc22e907f985d6a9e9dd1d4fbecae573549cf49350113e7757b1"
  FIELDS = [:data]

  attr_accessor :data

  def initialize(data: nil)
    @data = data.nil? ? 0 : data
  end

  def self.write(w, m)
    w.uint16(m.data)
  end

  def self.read(r)
    m = new
    m.data = r.uint16
    m
  end
end
